### ISSUE TITLE
missing module in server.py

### ISSUE THREAD

**Issue by Goeks1** [fastogt/fastocloud_admin#12]
Tried it with docker and without.
If I want to start server.py I receive the below error
My system is Debian 9

```
fastocloud_admin    | Traceback (most recent call last):
fastocloud_admin    |   File "./server.py", line 8, in <module>
fastocloud_admin    |     from app import app, servers_manager
fastocloud_admin    |   File "/app/app/__init__.py", line 12, in <module>
fastocloud_admin    |     from app.service.service_manager import ServiceManager
fastocloud_admin    |   File "/app/app/service/service_manager.py", line 1, in <module>
fastocloud_admin    |     from app.common.service.entry import ServiceSettings
fastocloud_admin    | ModuleNotFoundError: No module named 'app.common.service'
```

**Comment by topilski** [comment]
you forgot git submoudle update --init --recursive

**Comment by Goeks1** [comment]
```
root@scw-heuristic-hugle:~/fastocloud_admin# git submodule update --init --recursive
Submodule 'app/common' (https://github.com/fastogt/pyfastotv.git) registered for path 'app/common'
Cloning into '/root/fastocloud_admin/app/common'...
Submodule path 'app/common': checked out 'a0943287c30c433bb0513c7153a63a6f52afa54d'
root@scw-heuristic-hugle:~/fastocloud_admin# docker-compose up
Starting mongodb
Starting fastocloud
Starting fastocloud_admin
Starting nginx
Attaching to mongodb, fastocloud_admin, fastocloud, nginx
mongodb             | 2019-09-22T04:34:17.156+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongodb             | 2019-09-22T04:34:17.159+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=c131699c2aac
mongodb             | 2019-09-22T04:34:17.159+0000 I  CONTROL  [initandlisten] db version v4.2.0
mongodb             | 2019-09-22T04:34:17.159+0000 I  CONTROL  [initandlisten] git version: a4b751dcf51dd249c5865812b390cfd1c0129c30
mongodb             | 2019-09-22T04:34:17.159+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
mongodb             | 2019-09-22T04:34:17.159+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
mongodb             | 2019-09-22T04:34:17.159+0000 I  CONTROL  [initandlisten] modules: none
mongodb             | 2019-09-22T04:34:17.159+0000 I  CONTROL  [initandlisten] build environment:
mongodb             | 2019-09-22T04:34:17.159+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
mongodb             | 2019-09-22T04:34:17.160+0000 I  CONTROL  [initandlisten]     distarch: x86_64
mongodb             | 2019-09-22T04:34:17.160+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
mongodb             | 2019-09-22T04:34:17.160+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
mongodb             | 2019-09-22T04:34:17.160+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongodb             | 2019-09-22T04:34:17.160+0000 I  STORAGE  [initandlisten] 
mongodb             | 2019-09-22T04:34:17.160+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongodb             | 2019-09-22T04:34:17.160+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongodb             | 2019-09-22T04:34:17.160+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=31703M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
mongodb             | 2019-09-22T04:34:18.035+0000 I  STORAGE  [initandlisten] WiredTiger message [1569126858:35191][1:0x7f5245884b00], txn-recover: Recovering log 3 through 4
mongodb             | 2019-09-22T04:34:18.099+0000 I  STORAGE  [initandlisten] WiredTiger message [1569126858:99504][1:0x7f5245884b00], txn-recover: Recovering log 4 through 4
mongodb             | 2019-09-22T04:34:18.186+0000 I  STORAGE  [initandlisten] WiredTiger message [1569126858:186697][1:0x7f5245884b00], txn-recover: Main recovery loop: starting at 3/6272 to 4/256
mongodb             | 2019-09-22T04:34:18.309+0000 I  STORAGE  [initandlisten] WiredTiger message [1569126858:309337][1:0x7f5245884b00], txn-recover: Recovering log 3 through 4
mongodb             | 2019-09-22T04:34:18.388+0000 I  STORAGE  [initandlisten] WiredTiger message [1569126858:388882][1:0x7f5245884b00], txn-recover: Recovering log 4 through 4
mongodb             | 2019-09-22T04:34:18.454+0000 I  STORAGE  [initandlisten] WiredTiger message [1569126858:454930][1:0x7f5245884b00], txn-recover: Set global recovery timestamp: (0,0)
mongodb             | 2019-09-22T04:34:18.495+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongodb             | 2019-09-22T04:34:18.505+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
mongodb             | 2019-09-22T04:34:18.514+0000 I  CONTROL  [initandlisten] 
mongodb             | 2019-09-22T04:34:18.514+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongodb             | 2019-09-22T04:34:18.514+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongodb             | 2019-09-22T04:34:18.514+0000 I  CONTROL  [initandlisten] 
mongodb             | 2019-09-22T04:34:18.535+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
mongodb             | 2019-09-22T04:34:18.535+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
mongodb             | 2019-09-22T04:34:18.535+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
mongodb             | 2019-09-22T04:34:18.535+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
mongodb             | 2019-09-22T04:34:18.536+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
mongodb             | 2019-09-22T04:34:18.536+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongodb             | 2019-09-22T04:34:18.538+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
mongodb             | 2019-09-22T04:34:18.538+0000 I  NETWORK  [initandlisten] Listening on /tmp/mongodb-27017.sock
mongodb             | 2019-09-22T04:34:18.538+0000 I  NETWORK  [initandlisten] Listening on 0.0.0.0
mongodb             | 2019-09-22T04:34:18.538+0000 I  NETWORK  [initandlisten] waiting for connections on port 27017
mongodb             | 2019-09-22T04:34:18.538+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
fastocloud_admin    | Traceback (most recent call last):
fastocloud_admin    |   File "./server.py", line 8, in <module>
fastocloud_admin    |     from app import app, servers_manager
fastocloud_admin    |   File "/app/app/__init__.py", line 12, in <module>
fastocloud_admin    |     from app.service.service_manager import ServiceManager
fastocloud_admin    |   File "/app/app/service/service_manager.py", line 1, in <module>
fastocloud_admin    |     from app.common.service.entry import ServiceSettings
fastocloud_admin    | ModuleNotFoundError: No module named 'app.common.service'
fastocloud exited with code 1
fastocloud_admin exited with code 1

```

**Comment by topilski** [comment]
You need to rebuild docker-compose now

**Comment by Goeks1** [comment]
Thank you for the quick response! Indeed I have forgotten it.
