### ISSUE TITLE
./server py cannot import name 'make_utc_timestamp_seconds'

### ISSUE THREAD

**Issue by opaniagu** [fastogt/fastocloud_admin#24]
oscar@oscar-XPS-13-9360:~/iptv/fastocloud_admin$ ./server.py
Traceback (most recent call last):
  File "./server.py", line 8, in <module>
    from app import app, servers_manager
  File "/home/oscar/iptv/fastocloud_admin/app/__init__.py", line 13, in <module>
    from app.service.subscribers_service_manager import SubscribersServiceManager
  File "/home/oscar/iptv/fastocloud_admin/app/service/subscribers_service_manager.py", line 5, in <module>
    from app.service.subscriber_client import SubscriberConnection
  File "/home/oscar/iptv/fastocloud_admin/app/service/subscriber_client.py", line 3, in <module>
    from pyfastocloud.client import make_utc_timestamp_seconds
ImportError: cannot import name 'make_utc_timestamp_seconds' from 'pyfastocloud.client' (/usr/local/lib/python3.7/dist-packages/pyfastocloud/client.py)

**Comment by topilski** [comment]
You need to update pyfastocloud
