### ISSUE TITLE
fastocloud_admin docker image does not have pyfastogt

### ISSUE THREAD

**Issue by randomshinichi** [fastogt/fastocloud_admin#27]
The official Docker Hub image and an image built from the repo using `docker build .` does not run because it is missing pyfastogt.

```
shinichi@asuka:~/source/iptv/fastocloud_admin[master*] docker run -it fastogt/fastocloud_admin  /bin/bash
root@d53af391c8f3:/app# python server.py
Traceback (most recent call last):
  File "server.py", line 8, in <module>
    from app import app, servers_manager
  File "/app/app/__init__.py", line 99, in <module>
    from app.epg.view import EpgView
  File "/app/app/epg/view.py", line 9, in <module>
    from pyfastogt.utils import read_file_line_by_line_to_set
ModuleNotFoundError: No module named 'pyfastogt'
root@d53af391c8f3:/app# nano requirements.txt 
bash: nano: command not found
root@d53af391c8f3:/app# apt update; apt install nano; nano requirements.txt
Get:1 http://security.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [113 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7899 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [5792 B]
Fetched 8227 kB in 6s (1482 kB/s)                        
Reading package lists... Done
Building dependency tree       
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  spell
The following NEW packages will be installed:
  nano
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 544 kB of archives.
After this operation, 2269 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 nano amd64 3.2-3 [544 kB]
Fetched 544 kB in 0s (1883 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package nano.
(Reading database ... 24525 files and directories currently installed.)
Preparing to unpack .../archives/nano_3.2-3_amd64.deb ...
Unpacking nano (3.2-3) ...
Setting up nano (3.2-3) ...
update-alternatives: using /bin/nano to provide /usr/bin/editor (editor) in auto mode
update-alternatives: using /bin/nano to provide /usr/bin/pico (pico) in auto mode
root@d53af391c8f3:/app# pip install -r requirements.txt ; python server.py
Requirement already satisfied: flask>=1.0.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: flask_socketio>=1.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (4.2.1)
Requirement already satisfied: flask_mongoengine>=0.8.2 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (0.9.5)
Requirement already satisfied: flask_login>=0.3.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.4.1)
Requirement already satisfied: flask_mail>=0.7.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (0.9.1)
Requirement already satisfied: flask_bootstrap>=3.3.7.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (3.3.7.1)
Requirement already satisfied: flask_classy>=0.6.10 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (0.6.10)
Requirement already satisfied: validate_email>=1.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (1.3)
Requirement already satisfied: requests>=1.0.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (2.22.0)
Requirement already satisfied: wtforms>=2.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (2.2.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (2.8.1)
Requirement already satisfied: Flask-Babel>=0.11.2 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (0.12.2)
Requirement already satisfied: gevent>=1.1.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (1.4.0)
Requirement already satisfied: pyfastocloud from git+git://github.com/fastogt/pyfastocloud@master#egg=pyfastocloud in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (1.2.0)
Collecting pyfastogt
  Cloning git://github.com/fastogt/pyfastogt (to revision master) to /tmp/pip-install-d1h1r2pe/pyfastogt
  Running command git clone -q git://github.com/fastogt/pyfastogt /tmp/pip-install-d1h1r2pe/pyfastogt
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.8/site-packages (from flask>=1.0.0->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.8/site-packages (from flask>=1.0.0->-r requirements.txt (line 1)) (7.0)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.8/site-packages (from flask>=1.0.0->-r requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.8/site-packages (from flask>=1.0.0->-r requirements.txt (line 1)) (2.10.3)
Requirement already satisfied: python-socketio>=4.3.0 in /usr/local/lib/python3.8/site-packages (from flask_socketio>=1.0->-r requirements.txt (line 2)) (4.3.1)
Requirement already satisfied: Flask-WTF>=0.13 in /usr/local/lib/python3.8/site-packages (from flask_mongoengine>=0.8.2->-r requirements.txt (line 3)) (0.14.2)
Requirement already satisfied: mongoengine>=0.8.0 in /usr/local/lib/python3.8/site-packages (from flask_mongoengine>=0.8.2->-r requirements.txt (line 3)) (0.18.2)
Requirement already satisfied: six in /usr/local/lib/python3.8/site-packages (from flask_mongoengine>=0.8.2->-r requirements.txt (line 3)) (1.13.0)
Requirement already satisfied: blinker in /usr/local/lib/python3.8/site-packages (from flask_mail>=0.7.1->-r requirements.txt (line 5)) (1.4)
Requirement already satisfied: visitor in /usr/local/lib/python3.8/site-packages (from flask_bootstrap>=3.3.7.1->-r requirements.txt (line 6)) (0.1.3)
Requirement already satisfied: dominate in /usr/local/lib/python3.8/site-packages (from flask_bootstrap>=3.3.7.1->-r requirements.txt (line 6)) (2.4.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests>=1.0.0->-r requirements.txt (line 9)) (1.25.6)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests>=1.0.0->-r requirements.txt (line 9)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.8/site-packages (from requests>=1.0.0->-r requirements.txt (line 9)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests>=1.0.0->-r requirements.txt (line 9)) (2019.9.11)
Requirement already satisfied: Babel>=2.3 in /usr/local/lib/python3.8/site-packages (from Flask-Babel>=0.11.2->-r requirements.txt (line 12)) (2.7.0)
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in /usr/local/lib/python3.8/site-packages (from gevent>=1.1.0->-r requirements.txt (line 13)) (0.4.15)
Collecting distro
  Downloading https://files.pythonhosted.org/packages/ea/35/82f79b92fa4d937146c660a6482cee4f3dfa1f97ff3d2a6f3ecba33e712e/distro-1.4.0-py2.py3-none-any.whl
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.8/site-packages (from Jinja2>=2.10.1->flask>=1.0.0->-r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: python-engineio>=3.9.0 in /usr/local/lib/python3.8/site-packages (from python-socketio>=4.3.0->flask_socketio>=1.0->-r requirements.txt (line 2)) (3.10.0)
Requirement already satisfied: pymongo>=3.4 in /usr/local/lib/python3.8/site-packages (from mongoengine>=0.8.0->flask_mongoengine>=0.8.2->-r requirements.txt (line 3)) (3.9.0)
Requirement already satisfied: pytz>=2015.7 in /usr/local/lib/python3.8/site-packages (from Babel>=2.3->Flask-Babel>=0.11.2->-r requirements.txt (line 12)) (2019.3)
Building wheels for collected packages: pyfastogt
  Building wheel for pyfastogt (setup.py) ... done
  Created wheel for pyfastogt: filename=pyfastogt-1.1.0-cp38-none-any.whl size=13369 sha256=2e62f19ae95edbd295fd20dc534ede7bbdd5ee8d28ec650595dda8984711fa6d
  Stored in directory: /tmp/pip-ephem-wheel-cache-yiu4q3kk/wheels/1c/90/71/0d88054b06b06bfd17676cf3b878daf14427c881b685e41d8a
Successfully built pyfastogt
ERROR: pyfastogt 1.1.0 has requirement validate-email==1.0, but you'll have validate-email 1.3 which is incompatible.
Installing collected packages: distro, pyfastogt
Successfully installed distro-1.4.0 pyfastogt-1.1.0
```

**Comment by topilski** [comment]
Fixed
